seiya/spider/spiders/__init__.py
# This package will contain the spiders of your Scrapy project
#
# Please refer to the documentation for information on how to create and manage
# your spiders.

seiya/web/app.py
from flask import Flask
from seiya.web.config import configs
from seiya.web.blueprints import home_bp, job_bp, tenement_bp, movie_bp


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(configs.get(config))
    register_blueprints(app)
    return app


def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(job_bp)
    app.register_blueprint(tenement_bp)
    app.register_blueprint(movie_bp)

seiya/web/blueprints/__init__.py
from .home import home_bp
from .job import job_bp
from .tenement import tenement_bp
from .movie import movie_bp

seiya/web/blueprints/home.py
from flask import Blueprint, render_template


home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def index():
    return render_template('index.html')

@home_bp.route('/test')
def test():
    return render_template('test.html')

seiya/web/blueprints/job.py
from flask import Blueprint, render_template, jsonify
from seiya.analysis.job import (analysis_top10_city, analysis_top10_wage,
        analysis_tags, analysis_experience, analysis_education,
        analysis_cityedc_salary)


job_bp = Blueprint('job', __name__, url_prefix='/job')

@job_bp.route('/')
def index():
    return render_template('job/index.html')

@job_bp.route('/top10-city')
def top10_city():
    data = analysis_top10_city()
    return render_template('job/top10_city.html', city_data=data)

@job_bp.route('/top10-wage')
def top10_wage():
    data = analysis_top10_wage()
    return render_template('job/top10_wage.html', salary_data=data)

@job_bp.route('/top10-tag')
def top10_tag():
    data = analysis_tags()
    return render_template('job/top10_tag.html', tag_data=data)

@job_bp.route('/experience')
def experience():
    data = analysis_experience()
    return render_template('job/experience.html', experience_data=data)

@job_bp.route('/education')
def education():
    data = analysis_education()
    return render_template('job/education.html', education_data=data)

@job_bp.route('/city-edu-salary')
def cityedu_salary():
    data = analysis_cityedc_salary()
    return render_template('job/cityedu_salary.html', ces_data=data)

seiya/web/blueprints/movie.py
from flask import Blueprint, render_template
from seiya.analysis.movie import (analysis_review_num, analysis_country, 
        analysis_director)


movie_bp = Blueprint('movie', __name__, url_prefix='/movie')

@movie_bp.route('/')
def index():
    return render_template('movie/index.html')

@movie_bp.route('/review-num')
def review_num():
    data = analysis_review_num()
    return render_template('movie/review_num.html', review_data=data)

@movie_bp.route('/country')
def country():
    data = analysis_country()
    return render_template('movie/country.html', country_data=data)

@movie_bp.route('/director')
def director():
    data = analysis_director()
    return render_template('movie/director.html', director_data=data)

seiya/web/blueprints/tenement.py
from flask import Blueprint, render_template
from seiya.analysis.tenement import (analysis_top10_estate, analysis_unit,
        analysis_area, analysis_region, analysis_rent)


tenement_bp = Blueprint('tenement', __name__, url_prefix='/tenement')

@tenement_bp.route('/')
def index():
    return render_template('tenement/index.html')

@tenement_bp.route('/top10-estate')
def top10_estate():
    data = analysis_top10_estate()
    return render_template('tenement/top10_estate.html', estate_data=data)

@tenement_bp.route('/unit')
def unit():
    data = analysis_unit()
    return render_template('tenement/unit.html', unit_data=data)

@tenement_bp.route('/area')
def area():
    data = analysis_area()
    return render_template('tenement/area.html', area_data=data)

@tenement_bp.route('/region')
def region():
    data = analysis_region()
    return render_template('tenement/region.html', region_data=data)

@tenement_bp.route('/rent')
def rent():
    data = analysis_rent()
    return render_template('tenement/rent.html', rent_data=data)

seiya/web/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
   <script src="https://gw.alipayobjects.com/os/lib/antv/g2/3.4.10/dist/g2.min.js"></script>
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">Seiya</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
              data-target="#navbarSupportedContent" 
              aria-controls="navbarSupportedContent" 
              aria-expanded="false" 
              aria-label="Toggle navigation">
        <span class="navbar-toggle-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="{{ url_for('job.index') }}" 
               id="navbarDropdown" role="button" data-toggle="dropdown" 
               aria-haspopup="true" 
               aria-expanded="false">
              拉勾网职位数据分析
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" 
                 href="{{ url_for('job.top10_city') }}">热门工作城市</a>
              <a class="dropdown-item" 
                 href="{{ url_for('job.top10_wage') }}">薪资最高城市</a>
              <a class="dropdown-item" 
                 href="{{ url_for('job.top10_tag') }}">热门标签</a>
              <a class="dropdown-item" 
                 href="{{ url_for('job.experience') }}">工作经验统计</a>
              <a class="dropdown-item" 
                 href="{{ url_for('job.education') }}">学历要求统计</a>
              <a class="dropdown-item" 
                 href="{{ url_for('job.cityedu_salary') }}">
                 同等学历不同城市薪资对比</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" 
               id="navbarDropdown" role="button" data-toggle="dropdown" 
               aria-haspopup="true" 
               aria-expanded="false">
               链家网租房数据分析
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" 
                 href="{{ url_for('tenement.top10_estate') }}">
                 热门租房小区</a>
              <a class="dropdown-item" 
                 href="{{ url_for('tenement.unit') }}">户型分布</a>
              <a class="dropdown-item"
                 href="{{ url_for('tenement.area') }}">面积分布</a>
              <a class="dropdown-item" 
                 href="{{ url_for('tenement.region') }}">热门行政区</a>
              <a class="dropdown-item" 
                 href="{{ url_for('tenement.rent') }}">最贵小区</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" 
               id="navbarDropdown" role="button" data-toggle="dropdown" 
               aria-haspopup="true" 
               aria-expanded="false">
              豆瓣电影 TOP250 数据分析
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" 
                 href="{{ url_for('movie.review_num') }}">评论数 Top10</a>
              <a class="dropdown-item" 
                 href="{{ url_for('movie.country') }}">好片最多国家、地区 Top10</a>
              <a class="dropdown-item" 
                 href="{{ url_for('movie.director') }}">好片最多导演</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
   </nav>
   <div class="container">
     {% block body %}{% endblock %}
     {% block fotter %}{% endblock %}
   </div>
   {% block js %}
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   {% endblock %}
</body>
</html>

seiya/web/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
<br>
<div class="card mb-3">
  <img class="card-img-top" src="https://s2.ax1x.com/2019/04/24/EVIlqJ.jpg" alt="Card image cap">
  <div class="card-body">
      <h5 class="card-title"><a href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></h5>
    <p class="card-text">热门工作城市，薪资最高城市，热门职位标签，工作经验统计，学历要求统计，同等学历不同城市薪资对比。</p>
  </div>
</div>
<br>
<div class="card mb-3">
  <img class="card-img-top" src="https://s2.ax1x.com/2019/04/25/EekavT.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><a href="{{ url_for('tenement.index') }}">
        链家网租房数据分析</a></h5>
    <p class="card-text">热门租房小区，户型分布，面积分布，区域统计，最贵小区</p>
  </div>
</div>
<br>
<div class="card mb-3">
  <img class="card-img-top" src="https://s2.ax1x.com/2019/04/25/EeApIs.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><a href="{{ url_for('movie.index') }}">
        豆瓣电影 TOP250 数据分析</a></h5>
    <p class="card-text">评论数量 Top10，好片最多国家、地区，好片最多导演</p>
  </div>
</div>
{% endblock %}

seiya/web/templates/job/cityedu_salary.html
{% extends "base.html" %}

{% block title %}薪资对比{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">
        同等学历不同城市薪资对比</li>
  </ol>
</nav>
<br>
<div id="mountNode"></div>
<script>
  var data = {{ ces_data|tojson|safe }}

  var chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: 400
  });
  chart.source(data, {
    edu: {
      range: [0, 1]
    }
  });
  chart.tooltip({
    crosshairs: {
      type: 'line'
    }
  });
  chart.axis('salary', {
    label: {
      formatter: function formatter(val) {
        return val + 'k';
      }
    }
  });
  chart.line().position('city*salary').color('edc');
  chart.point().position('city*salary').color('edc').size(4).shape('circle').style({
    stroke: '#fff',
    lineWidth: 1
  });
  chart.render();
</script>
{% endblock %}

seiya/web/templates/job/education.html
{% extends "base.html" %}

{% block title %}学历要求{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">学历要求统计</li>
  </ol>
</nav>
<br>
<div id="mountNode"></div>
<script>
  var data = {{ education_data|tojson|safe }}

  var chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: 400
  });
  chart.source(data, {
    percent: {
      formatter: function formatter(val) {
        val = val * 100 + '%';
        return val;
      }
    }
  });
  chart.coord('theta', {
    radius: 0.75
  });
  chart.tooltip({
    showTitle: false,
    itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
  });
  chart.intervalStack().position('percent').color('item').label('percent', {
    formatter: function formatter(val, item) {
      return item.point.item + ': ' + val;
    }
  }).tooltip('item*percent', function(item, percent) {
    percent = percent * 100 + '%';
    return {
      name: item,
      value: percent
    };
  }).style({
    lineWidth: 1,
    stroke: '#fff'
  });
  chart.render();
</script>
{% endblock %}

seiya/web/templates/job/experience.html
{% extends "base.html" %}

{% block title %}工作经验{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">工作经验统计</li>
  </ol>
</nav>
<br>
<div id="mountNode"></div>
<script>
  var data = {{ experience_data|tojson|safe }}

  var chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: 400,
    padding: [40, 0]
  });

  chart.source(data);
  chart.coord('theta', {
    startAngle: Math.PI,
    endAngle: Math.PI * (3 / 2) 
  });
  chart.intervalStack().position('count').color('experience').label('experience');

  chart.render();
</script>
{% endblock %}

seiya/web/templates/job/index.html
{% extends "base.html" %}

{% block title %}JOB{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item active" aria-current="page">拉勾网职位数据分析</li>
  </ol>
</nav>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">热门工作城市</h5>
        <p class="card-text">职位数 Top10 城市</p>
        <a href="{{ url_for('job.top10_city') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">薪资最高城市</h5>
        <p class="card-text">薪资 Top10 城市</p>
        <a href="{{ url_for('job.top10_wage') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">热门标签</h5>
        <p class="card-text">热门标签 Top10.</p>
        <a href="{{ url_for('job.top10_tag') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">工作经验统计</h5>
        <p class="card-text">工作经验要求一览</p>
        <a href="{{ url_for('job.experience') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">学历要求统计</h5>
        <p class="card-text">学历要求一览</p>
        <a href="{{ url_for('job.education') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">同等学历不同城市薪资对比</h5>
        <p class="card-text">城市薪资一览</p>
        <a href="{{ url_for('job.cityedu_salary') }}" 
           class="btn btn-primary">Button</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

seiya/web/templates/job/top10_city.html
{% extends "base.html" %}

{% block title %}热门工作城市{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">职位数 Top10 城市</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ city_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 800,
  height: 400,
});
chart.source(data);
chart.interval().position("name*amount").color("name")
chart.render();
</script>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">城市</th>
      <th scope="col">职位数</th>
    </tr>
  </thead>
  <tbody>
    {% for value in city_data %}
    <tr>
      <td>{{ city_data.index(value) + 1 }}</td>
      <td>{{ value['name'] }}</td>
      <td>{{ value['amount'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/job/top10_tag.html
{% extends "base.html" %}

{% block title %}热门标签{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">热门标签</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ tag_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 800,
  height: 400,
});
chart.source(data);
chart.interval().position("tag*count").color("tag")
chart.render();
</script>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">标签</th>
      <th scope="col">次数</th>
    </tr>
  </thead>
  <tbody>
    {% for value in tag_data %}
    <tr>
      <td>{{ tag_data.index(value) + 1 }}</td>
      <td>{{ value['tag'] }}</td>
      <td>{{ value['count'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/job/top10_wage.html
{% extends "base.html" %}

{% block title %}薪资最高城市{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('job.index') }}">拉勾网职位数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">薪资 Top10 城市</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ salary_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 800,
  height: 400,
});
chart.source(data);
chart.interval().position("name*salary").color("name")
chart.render();
</script>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">城市</th>
      <th scope="col">薪资</th>
    </tr>
  </thead>
  <tbody>
    {% for value in salary_data %}
    <tr>
      <td>{{ salary_data.index(value) + 1 }}</td>
      <td>{{ value['name'] }}</td>
      <td>{{ value['salary'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/movie/country.html
{% extends "base.html" %}

{% block title %}国家、地区{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('movie.index') }}">豆瓣电影 TOP250 数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">好片最多国家、地区 Top10</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ country_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 900,
  height: 400,
});
chart.source(data);
chart.interval().position("name*count").color("name")
chart.render();
</script>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">国家</th>
      <th scope="col">电影数量</th>
    </tr>
  </thead>
  <tbody>
    {% for value in country_data %}
    <tr>
      <td>{{ country_data.index(value) + 1 }}</td>
      <td>{{ value['name'] }}</td>
      <td>{{ value['count'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/movie/director.html
{% extends "base.html" %}

{% block title %}导演{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('movie.index') }}">豆瓣电影 TOP250 数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">好片最多的导演排名</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ director_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 950,
  height: 450,
});
chart.source(data);
chart.interval().position("name*count").color("name")
chart.render();
</script>
<br>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">导演</th>
      <th scope="col">电影数量</th>
    </tr>
  </thead>
  <tbody>
    {% for value in director_data %}
    <tr>
      <td>{{ director_data.index(value) + 1 }}</td>
      <td>{{ value['name'] }}</td>
      <td>{{ value['count'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/movie/index.html
{% extends "base.html" %}

{% block title %}Movie{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item active" aria-current="page">豆瓣电影 TOP250 数据分析</li>
  </ol>
</nav>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">评论数 Top10</h5>
        <p class="card-text">最火热的TOP250</p>
        <a href="{{ url_for('movie.review_num') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">好片最多国家、地区</h5>
        <p class="card-text">Top10 好片最多国家、地区</p>
        <a href="{{ url_for('movie.country') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">好片最多导演</h5>
        <p class="card-text">出品数大于两部的导演</p>
        <a href="{{ url_for('movie.director') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
</div>
{% endblock %}

seiya/web/templates/movie/review_num.html
{% extends "base.html" %}

{% block title %}评论数{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item"><a 
        href="{{ url_for('movie.index') }}">豆瓣电影 TOP250 数据分析</a></li>
    <li class="breadcrumb-item active" aria-current="page">评论数 Top10</li>
  </ol>
</nav>
<br>
<center>
<div id="c1"></div>
<script>

const data= {{ review_data|tojson|safe }};

const chart = new G2.Chart({
  container: "c1",
  width: 900,
  height: 400,
});
chart.source(data);
chart.interval().position("name*num").color("name")
chart.render();
</script>
<table class="table table-sm table-borderless">
  <thead class="thead-light">
    <tr>
      <th scope="col">排名</th>
      <th scope="col">电影</th>
      <th scope="col">评论数</th>
    </tr>
  </thead>
  <tbody>
    {% for value in review_data %}
    <tr>
      <td>{{ review_data.index(value) + 1 }}</td>
      <td>{{ value['name'] }}</td>
      <td>{{ value['num'] }}</td>
    </tr>
    {% endfor %}
</center>
{% endblock %}

seiya/web/templates/tenement/index.html
{% extends "base.html" %}

{% block title %}Tenement{% endblock %}

{% block body %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">首页</a></li>
    <li class="breadcrumb-item active" aria-current="page">链家网租房数据分析</li>
  </ol>
</nav>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">热门租房小区</h5>
        <p class="card-text">Top10 租房小区</p>
        <a href="{{ url_for('tenement.top10_estate') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">户型分布</h5>
        <p class="card-text">户型分布分析</p>
        <a href="{{ url_for('tenement.unit') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">面积分布</h5>
        <p class="card-text">面积分布分析</p>
        <a href="{{ url_for('tenement.area') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">热门行政区</h5>
        <p class="card-text">热门行政区 Top10</p>
        <a href="{{ url_for('tenement.region') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">最贵小区</h5>
        <p class="card-text">最贵小区一览</p>
        <a href="{{ url_for('tenement.rent') }}" 
           class="btn btn-primary">View</a>
      </div>
    </div>
  <br>
  </div> 
</div>
{% endblock %}